columns:
  ID: int64   
  LIMIT_BAL: float64   
  SEX: int64 
  EDUCATION: int64   
  MARRIAGE: int64   
  AGE: int64   
  PAY_0: int64   
  PAY_2: int64   
  PAY_3: int64   
  PAY_4: int64   
  PAY_5: int64   
  PAY_6: int64   
  BILL_AMT1: float64   
  BILL_AMT2: float64   
  BILL_AMT3: float64   
  BILL_AMT4: float64   
  BILL_AMT5: float64   
  BILL_AMT6: float64   
  PAY_AMT1: float64   
  PAY_AMT2: float64   
  PAY_AMT3: float64   
  PAY_AMT4: float64   
  PAY_AMT5: float64   
  PAY_AMT6: float64   
  default.payment.next.month: int64 

numerical_columns:
  - ID        
  - LIMIT_BAL        
  - SEX      
  - EDUCATION        
  - MARRIAGE        
  - AGE        
  - PAY_0        
  - PAY_2
  - PAY_3        
  - PAY_4        
  - PAY_5        
  - PAY_6        
  - BILL_AMT1        
  - BILL_AMT2        
  - BILL_AMT3        
  - BILL_AMT4        
  - BILL_AMT5        
  - BILL_AMT6        
  - PAY_AMT1        
  - PAY_AMT2        
  - PAY_AMT3        
  - PAY_AMT4        
  - PAY_AMT5        
  - PAY_AMT6  

target_column: default.payment.next.month